"""add language posts

Revision ID: 855de7b49c2e
Revises: 0b3190c3af83
Create Date: 2024-07-31 18:06:20.579371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855de7b49c2e'
down_revision = '0b3190c3af83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
